### ISSUE TITLE
durable objects を触る

### ISSUE THREAD

**Issue by naporin0624** [napolab/cloudflare-workers-playground#4]
Hono を入れた上で使う方法は以下
https://github.com/honojs/examples/blob/main/durable-objects/src/counter.ts

**Comment by naporin0624** [comment]
counter と webSocket client の永続化をする singleton instance として扱うやり方を学習した

```typescript
import { Hono } from "hono";

import { wsupgrade } from "../middleware";

export class SharedEvent implements DurableObject {
  private readonly app = new Hono();
  private readonly sessions = new Set<WebSocket>();

  constructor(private readonly state: DurableObjectState) {
    this.app.get("/events", wsupgrade(), async (c) => {
      const pair = new WebSocketPair();
      this.handleSession(pair[1]);

      return new Response(null, { status: 101, webSocket: pair[0] });
    });
    this.app.post("/event", async (c) => {
      const data = await c.req.json();
      const json = JSON.stringify(data);
      for (const socket of this.sessions) {
        socket.send(json);
      }
    });
  }

  private handleSession(socket: WebSocket): void {
    socket.accept();
    this.sessions.add(socket);

    socket.addEventListener("close", () => {
      this.sessions.delete(socket);
      socket.close();
    });
  }

  fetch(request: Request) {
    return this.app.fetch(request);
  }
}
```

**Comment by naporin0624** [comment]
durable objects を扱ううえで wrangler.toml が若干面倒なのでメモを残しておく

https://developers.cloudflare.com/workers/learning/using-durable-objects/#durable-object-migrations-in-wranglertoml

```toml
[durable_objects]
bindings = [
  # name は env に生える field, class_name は entrypoint から durable object class がどの名前で export されているかを指す
  { name = "XXX_XXX", class_name = "XxxXxx"
]

[[migrations]]
tag = "v1" # ここは migrations ごとに unique でなくてはならない
new_classes = ["Xxx"] # new_classes, rename_classes ,deleted_classes がある
```
